import { customAlphabet } from "nanoid";

// nanoid's default alphabet is URL-safe (alphanumerics + `-` + `_`). We
// drop both punctuation chars: `-` collides with parsers that treat dashes
// as field separators, and `_` looks doubled against the literal prefix
// (`hydra_session__foo`). Plain alphanumeric is plenty of entropy at
// length 16 (~95 bits).
const HYDRA_ID_ALPHABET =
  "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
const generateHydraId = customAlphabet(HYDRA_ID_ALPHABET, 16);

export const HYDRA_SESSION_PREFIX = "hydra_session_";

// Display helper: strip the constant prefix from auto-generated session ids
// so the random tail is what users see in lists and pickers. Foreign ids
// (anything not generated by us) pass through untouched.
export function stripHydraSessionPrefix(id: string): string {
  return id.startsWith(HYDRA_SESSION_PREFIX)
    ? id.slice(HYDRA_SESSION_PREFIX.length)
    : id;
}
import { AgentInstance } from "./agent-instance.js";
import {
  HYDRA_COMMANDS,
  hydraCommandsAsAdvertised,
  type AdvertisedCommand,
} from "./hydra-commands.js";
import type { HistoryEntry, HistoryStore } from "./history-store.js";
import type { JsonRpcConnection } from "../acp/connection.js";
import type { HistoryPolicy, JsonRpcId } from "../acp/types.js";
import { JsonRpcErrorCodes } from "../acp/types.js";

export interface AttachedClient {
  clientId: string;
  connection: JsonRpcConnection;
  clientInfo?: { name: string; version?: string };
}

export type CachedNotification = HistoryEntry;

export interface SpawnReplacementAgentParams {
  agentId: string;
  cwd: string;
  agentArgs?: string[];
}

export interface SpawnReplacementAgentResult {
  agent: AgentInstance;
  upstreamSessionId: string;
  agentMeta?: Record<string, unknown>;
}

export type SpawnReplacementAgent = (
  params: SpawnReplacementAgentParams,
) => Promise<SpawnReplacementAgentResult>;

export interface SessionInit {
  cwd: string;
  agentId: string;
  agent: AgentInstance;
  upstreamSessionId: string;
  title?: string;
  sessionId?: string;
  agentMeta?: Record<string, unknown>;
  agentArgs?: string[];
  idleTimeoutMs?: number;
  // Optional callback used by /hydra switch to spawn a fresh agent
  // process and run initialize + session/new on it. Provided by
  // SessionManager so Session doesn't have to depend on the registry.
  spawnReplacementAgent?: SpawnReplacementAgent;
  // History loaded from a prior cold incarnation of this session. When
  // set, the in-memory broadcast cache starts pre-populated so the
  // attaching client's replay matches what they'd have seen if the
  // session had stayed hot.
  seedHistory?: CachedNotification[];
  // When provided, every recordAndBroadcast entry is persisted to disk
  // so the session's history survives going cold.
  historyStore?: HistoryStore;
  // Snapshot state restored from meta.json on cold resurrect, so the
  // first attach response can deliver the right model/mode/commands
  // via _meta before the agent re-emits.
  currentModel?: string;
  currentMode?: string;
  agentCommands?: AdvertisedCommand[];
  // Suppress the first-prompt title heuristic. Set by SessionManager
  // when resurrecting a session whose title is already meaningful (from
  // a prior life's prompt seed, /hydra title, or regenTitle) — without
  // this, the next prompt would clobber the persisted title.
  firstPromptSeeded?: boolean;
}

export interface CloseOptions {
  deleteRecord?: boolean;
  // Before tearing the agent down, ask it for a fresh title that
  // summarises the conversation so far. Used by the idle-timeout path so
  // a session going cold persists a meaningful title for the picker.
  // Best-effort: failures are swallowed and the close proceeds.
  regenTitle?: boolean;
  // Maximum time to wait for the title regen before giving up and
  // killing the agent anyway. Defaults to 5 seconds.
  regenTitleTimeoutMs?: number;
}

export class Session {
  readonly sessionId: string;
  readonly cwd: string;
  // agent / agentId / upstreamSessionId are mutable so /hydra switch can
  // replace the underlying agent process while keeping the same Session
  // record. agentMeta is the metadata returned by the agent at session/new
  // time; it gets refreshed on switch too.
  agentId: string;
  agent: AgentInstance;
  upstreamSessionId: string;
  agentMeta: Record<string, unknown> | undefined;
  readonly agentArgs: string[] | undefined;
  title: string | undefined;
  // Snapshot state delivered to attaching clients via the attach
  // response _meta rather than via history replay (which would be
  // stale-prone for snapshot-shaped events).
  currentModel: string | undefined;
  currentMode: string | undefined;
  updatedAt: number;

  private clients = new Map<string, AttachedClient>();
  private history: CachedNotification[] = [];
  private historyStore: HistoryStore | undefined;
  private promptQueue: Array<() => Promise<void>> = [];
  private promptInFlight = false;
  private closed = false;
  private closeHandlers: Array<(opts: { deleteRecord: boolean }) => void> = [];
  private titleHandlers: Array<(title: string) => void> = [];
  // Subscribers notified after every entry that's actually persisted to
  // history (skipping snapshot-shaped events filtered by
  // recordAndBroadcast). The HTTP /v1/sessions/:id/history?follow=1
  // endpoint uses this to tail a live session's conversation stream
  // without participating in turns or prompts.
  private broadcastHandlers: Array<(entry: CachedNotification) => void> = [];
  // True once we've observed our first session/prompt; gates the
  // first-prompt-seeded title so subsequent prompts don't churn it.
  private firstPromptSeeded = false;
  // Permission requests that have been broadcast to one or more
  // clients but have not yet resolved. Replayed to clients that
  // attach mid-flight so a late joiner sees the prompt instead of an
  // empty session waiting on something they can't see. Settled entries
  // are removed so this map only ever contains live requests.
  private inFlightPermissions = new Set<{
    addClient: (client: AttachedClient) => void;
  }>();
  // While set, agent-emitted session/update notifications are
  // captured into `chunks` and NOT broadcast to clients. Used by
  // /hydra slash-command sub-prompts (e.g. title regeneration) so
  // the conversation log doesn't get polluted with the meta-prompt
  // and its reply.
  private internalPromptCapture: { chunks: string[] } | undefined;
  private idleTimeoutMs: number;
  private idleTimer: NodeJS.Timeout | undefined;
  private spawnReplacementAgent: SpawnReplacementAgent | undefined;
  private agentChangeHandlers: Array<
    (info: { agentId: string; upstreamSessionId: string }) => void
  > = [];
  // Last available_commands_update we observed from the agent. Stored
  // so we can re-broadcast a merged (hydra ∪ agent) list whenever
  // either half changes, and persisted to meta.json so a fresh attach
  // can deliver the merged list via _meta without depending on history
  // replay.
  private agentAdvertisedCommands: AdvertisedCommand[] = [];
  // Persist hooks for snapshot-shaped state. SessionManager hooks these
  // to mirror changes into meta.json so cold-resurrect attaches can
  // surface the latest snapshot via the attach response _meta.
  private agentCommandsHandlers: Array<
    (commands: AdvertisedCommand[]) => void
  > = [];
  private modelHandlers: Array<(model: string) => void> = [];
  private modeHandlers: Array<(mode: string) => void> = [];

  constructor(init: SessionInit) {
    this.sessionId =
      init.sessionId ?? `${HYDRA_SESSION_PREFIX}${generateHydraId()}`;
    this.cwd = init.cwd;
    this.agentId = init.agentId;
    this.agent = init.agent;
    this.upstreamSessionId = init.upstreamSessionId;
    this.agentMeta = init.agentMeta;
    this.agentArgs = init.agentArgs;
    this.title = init.title;
    this.currentModel = init.currentModel;
    this.currentMode = init.currentMode;
    if (init.agentCommands && init.agentCommands.length > 0) {
      this.agentAdvertisedCommands = [...init.agentCommands];
    }
    this.idleTimeoutMs = init.idleTimeoutMs ?? 0;
    this.spawnReplacementAgent = init.spawnReplacementAgent;
    if (init.firstPromptSeeded) {
      this.firstPromptSeeded = true;
    }
    this.historyStore = init.historyStore;
    if (init.seedHistory && init.seedHistory.length > 0) {
      this.history = [...init.seedHistory];
    }
    this.updatedAt = Date.now();

    this.wireAgent(this.agent);
  }

  private broadcastMergedCommands(): void {
    const merged: AdvertisedCommand[] = [
      ...hydraCommandsAsAdvertised(),
      ...this.agentAdvertisedCommands,
    ];
    this.recordAndBroadcast("session/update", {
      sessionId: this.upstreamSessionId,
      update: {
        sessionUpdate: "available_commands_update",
        availableCommands: merged,
      },
    });
  }

  // Register session/update, session/request_permission, and onExit
  // handlers on an agent connection. Re-run on every /hydra switch so
  // the new agent is plumbed identically. The exit handler's identity
  // check is what makes switching safe: when the *old* agent exits as
  // part of a swap, this.agent has already been replaced, so we no-op
  // and don't tear the session down.
  private wireAgent(agent: AgentInstance): void {
    agent.connection.onNotification("session/update", (params) => {
      // /hydra slash-command sub-prompts (e.g. title regeneration)
      // run "behind the scenes" — the agent's chunks for those are
      // captured into a private buffer instead of being broadcast.
      if (this.internalPromptCapture) {
        captureInternalChunk(this.internalPromptCapture, params);
        return;
      }
      // available_commands_update is intercepted: cache the agent's
      // list, persist to meta.json (so resurrect can deliver via _meta),
      // and re-emit a merged (hydra ∪ agent) version live. The merged
      // broadcast itself is filtered from history persistence by
      // recordAndBroadcast — clients learn the current commands either
      // live or via attach response _meta.
      const agentCmds = extractAdvertisedCommands(params);
      if (agentCmds !== null) {
        this.setAgentAdvertisedCommands(agentCmds);
        return;
      }
      // current_model_update / current_mode_update are similarly
      // snapshot-shaped: cache, persist, broadcast (but filtered from
      // history). The broadcast still fires so live clients see the
      // change immediately; new attaches get it via _meta.
      if (this.maybeApplyAgentModel(params)) {
        this.recordAndBroadcast("session/update", params);
        return;
      }
      if (this.maybeApplyAgentMode(params)) {
        this.recordAndBroadcast("session/update", params);
        return;
      }
      // Pick up agent-emitted session_info_update so the canonical
      // title in this Session matches what clients see broadcast.
      // Forwarded as-is through recordAndBroadcast below.
      this.maybeApplyAgentSessionInfo(params);
      this.recordAndBroadcast("session/update", params);
    });
    agent.connection.onRequest("session/request_permission", async (params) => {
      return this.handlePermissionRequest(params);
    });
    agent.onExit(() => {
      if (this.agent !== agent) {
        return;
      }
      this.markClosed({ deleteRecord: false });
    });
  }

  onAgentChange(
    handler: (info: { agentId: string; upstreamSessionId: string }) => void,
  ): void {
    this.agentChangeHandlers.push(handler);
  }

  get attachedCount(): number {
    return this.clients.size;
  }

  // Wall-clock when the in-flight agent turn began, or undefined when
  // idle. Derived from history: the most recent prompt_received without
  // a later turn_complete is the outstanding turn, and its recordedAt
  // is when the prompt was first broadcast. Used by buildResponseMeta
  // so a fresh client reattaching mid-turn boots up with the busy
  // banner showing real elapsed time.
  get turnStartedAt(): number | undefined {
    for (let i = this.history.length - 1; i >= 0; i--) {
      const entry = this.history[i];
      if (!entry) {
        continue;
      }
      const params = entry.params as { update?: { sessionUpdate?: string } };
      const kind = params?.update?.sessionUpdate;
      if (kind === "turn_complete") {
        return undefined;
      }
      if (kind === "prompt_received") {
        return entry.recordedAt;
      }
    }
    return undefined;
  }

  // Snapshot of the current in-memory replay history. Used by the
  // HTTP history endpoint to deliver the "what's accumulated so far"
  // prefix before optionally tailing with onBroadcast. Returns a copy
  // so callers can't mutate our cache.
  getHistorySnapshot(): CachedNotification[] {
    return [...this.history];
  }

  // Subscribe to recordable broadcast entries — fires once per entry
  // that lands in history (so snapshot-shaped session_info/model/mode/
  // available_commands updates do NOT trigger this; they're broadcast
  // live but not recorded). Returns an unsubscribe function the caller
  // must invoke when done.
  onBroadcast(handler: (entry: CachedNotification) => void): () => void {
    this.broadcastHandlers.push(handler);
    return () => {
      const i = this.broadcastHandlers.indexOf(handler);
      if (i >= 0) {
        this.broadcastHandlers.splice(i, 1);
      }
    };
  }

  attach(client: AttachedClient, historyPolicy: HistoryPolicy): CachedNotification[] {
    if (this.closed) {
      throw withCode(
        new Error("session is closed"),
        JsonRpcErrorCodes.SessionNotFound,
      );
    }
    if (this.clients.has(client.clientId)) {
      throw withCode(
        new Error(`client ${client.clientId} is already attached`),
        JsonRpcErrorCodes.AlreadyAttached,
      );
    }
    this.clients.set(client.clientId, client);
    this.updatedAt = Date.now();
    this.cancelIdleTimer();
    if (historyPolicy === "none") {
      return [];
    }
    if (historyPolicy === "pending_only") {
      return [];
    }
    return [...this.history];
  }

  // Dispatch in-flight permission requests to a freshly-attached
  // client. Called by the daemon's WS handler *after* it finishes
  // replaying history, so the prompt lands at the bottom of the
  // transcript rather than above the conversation.
  replayPendingPermissions(client: AttachedClient): void {
    for (const pending of this.inFlightPermissions) {
      pending.addClient(client);
    }
  }

  detach(clientId: string): void {
    if (this.clients.delete(clientId)) {
      this.updatedAt = Date.now();
      this.maybeStartIdleTimer();
    }
  }

  async prompt(clientId: string, params: unknown): Promise<unknown> {
    const client = this.clients.get(clientId);
    if (!client) {
      throw withCode(
        new Error("client not attached"),
        JsonRpcErrorCodes.SessionNotFound,
      );
    }
    // Slash commands (e.g. "/hydra title", "/hydra title some name")
    // are intercepted before any broadcasting or first-prompt seeding.
    // They never reach the agent as a normal turn — hydra dispatches
    // them, optionally runs a side-channel sub-prompt, and emits
    // whatever notifications the verb implies (e.g. session_info_update
    // for /hydra title). The conversation log stays clean.
    const promptText = extractPromptText(
      ((params ?? {}) as { prompt?: unknown }).prompt,
    ).trim();
    if (promptText.startsWith("/hydra")) {
      return this.handleSlashCommand(promptText);
    }
    this.broadcastPromptReceived(client, params);
    this.maybeSeedTitleFromPrompt(params);
    return this.enqueuePrompt(async () => {
      // We always pair broadcastPromptReceived with a broadcastTurnComplete,
      // even when the agent request throws. The recorded history is what
      // late-joining clients replay on attach — leaving prompts unmatched
      // means the next turn's keyed blocks anchor mid-scrollback (the
      // TUI freezes them as "thought · Xs" but never closes the
      // logical turn). A synthetic stopReason here surfaces the failure
      // to history without burying the trail.
      let response: unknown;
      try {
        response = await this.agent.connection.request<unknown>(
          "session/prompt",
          {
            ...(params as object),
            sessionId: this.upstreamSessionId,
          },
        );
      } catch (err) {
        this.broadcastTurnComplete(client.clientId, { stopReason: "error" });
        throw err;
      }
      this.broadcastTurnComplete(client.clientId, response);
      return response;
    });
  }

  private broadcastPromptReceived(
    client: AttachedClient,
    params: unknown,
  ): void {
    const promptParams = (params ?? {}) as Record<string, unknown>;
    const sentBy: Record<string, unknown> = { clientId: client.clientId };
    if (client.clientInfo?.name) {
      sentBy.name = client.clientInfo.name;
    }
    if (client.clientInfo?.version) {
      sentBy.version = client.clientInfo.version;
    }
    this.recordAndBroadcast(
      "session/update",
      {
        sessionId: this.sessionId,
        update: {
          sessionUpdate: "prompt_received",
          prompt: promptParams.prompt,
          sentBy,
        },
      },
      client.clientId,
    );

    // Compat shim for clients that don't yet implement RFD #533's
    // prompt_received. The marker in _meta lets prompt_received-aware
    // clients short-circuit this duplicate.
    const text = extractPromptText(promptParams.prompt);
    if (text.length > 0) {
      this.recordAndBroadcast(
        "session/update",
        {
          sessionId: this.sessionId,
          update: {
            sessionUpdate: "user_message_chunk",
            content: { type: "text", text },
            _meta: { "hydra-acp": { compatFor: "prompt_received" } },
          },
        },
        client.clientId,
      );
    }
  }

  private broadcastTurnComplete(
    originatorClientId: string,
    response: unknown,
  ): void {
    const stopReason =
      response &&
      typeof response === "object" &&
      "stopReason" in response &&
      typeof (response as { stopReason: unknown }).stopReason === "string"
        ? (response as { stopReason: string }).stopReason
        : undefined;
    const update: Record<string, unknown> = {
      sessionUpdate: "turn_complete",
    };
    if (stopReason !== undefined) {
      update.stopReason = stopReason;
    }
    this.recordAndBroadcast(
      "session/update",
      {
        sessionId: this.sessionId,
        update,
      },
      originatorClientId,
    );
  }

  async cancel(clientId: string): Promise<void> {
    const client = this.clients.get(clientId);
    if (!client) {
      throw withCode(
        new Error("client not attached"),
        JsonRpcErrorCodes.SessionNotFound,
      );
    }
    // session/cancel is a notification per the ACP spec — agents process it
    // and don't reply. Sending it as a request would hang our promise
    // forever waiting for a response that never comes.
    await this.agent.connection.notify("session/cancel", {
      sessionId: this.upstreamSessionId,
    });
  }

  async forwardRequest(method: string, params: unknown): Promise<unknown> {
    return this.agent.connection.request(method, this.rewriteForAgent(params));
  }

  private rewriteForAgent(params: unknown): unknown {
    if (params && typeof params === "object" && !Array.isArray(params)) {
      const obj = params as Record<string, unknown>;
      if (obj.sessionId === this.sessionId) {
        return { ...obj, sessionId: this.upstreamSessionId };
      }
    }
    return params;
  }

  async close(opts: CloseOptions = {}): Promise<void> {
    if (this.closed) {
      return;
    }
    this.cancelIdleTimer();
    if (opts.regenTitle && this.firstPromptSeeded) {
      const timeoutMs = opts.regenTitleTimeoutMs ?? 5000;
      await Promise.race([
        this.runTitleRegen().catch(() => undefined),
        new Promise<void>((r) => setTimeout(r, timeoutMs).unref?.()),
      ]);
    }
    await this.agent.kill().catch(() => undefined);
    this.markClosed({ deleteRecord: opts.deleteRecord ?? false });
  }

  onClose(handler: (opts: { deleteRecord: boolean }) => void): void {
    this.closeHandlers.push(handler);
  }

  // Subscribe to title updates. The SessionManager hooks this to
  // persist the new title to disk so a daemon restart restores it.
  onTitleChange(handler: (title: string) => void): void {
    this.titleHandlers.push(handler);
  }

  // Update the canonical title and broadcast a session_info_update to
  // every attached client. Clients that already speak the spec's
  // session_info_update need no hydra-specific wiring to pick this up.
  // Idempotent on identical values.
  private setTitle(title: string): void {
    const trimmed = title.trim();
    if (!trimmed || trimmed === this.title) {
      return;
    }
    this.title = trimmed;
    this.recordAndBroadcast("session/update", {
      sessionId: this.sessionId,
      update: {
        sessionUpdate: "session_info_update",
        title: trimmed,
        updatedAt: new Date().toISOString(),
      },
    });
    for (const handler of this.titleHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
  }

  // First-prompt heuristic: derive a session title from the first
  // session/prompt's text. Replaces whatever was set at session/new
  // (typically an editor frame name like "Claude Agent @ hydra-acp")
  // — the first prompt is a better summary for cross-client display
  // than the editor's static frame label. Subsequent prompts don't
  // touch the title; that'd flap as conversations evolved.
  private maybeSeedTitleFromPrompt(params: unknown): void {
    if (this.firstPromptSeeded) {
      return;
    }
    const promptParams = (params ?? {}) as { prompt?: unknown };
    const text = extractPromptText(promptParams.prompt);
    const seed = firstLine(text, 200);
    if (!seed) {
      return;
    }
    this.firstPromptSeeded = true;
    this.setTitle(seed);
  }

  // Apply an agent-emitted current_model_update. Returns true if the
  // notification was a model update (caller still needs to broadcast
  // it). Returns false otherwise so the caller can try the next kind.
  private maybeApplyAgentModel(params: unknown): boolean {
    const obj = (params ?? {}) as { update?: unknown };
    const update = (obj.update ?? {}) as {
      sessionUpdate?: unknown;
      currentModel?: unknown;
      model?: unknown;
    };
    if (update.sessionUpdate !== "current_model_update") {
      return false;
    }
    const raw =
      typeof update.currentModel === "string"
        ? update.currentModel
        : typeof update.model === "string"
        ? update.model
        : undefined;
    if (raw === undefined) {
      return true;
    }
    const trimmed = raw.trim();
    if (!trimmed || trimmed === this.currentModel) {
      return true;
    }
    this.currentModel = trimmed;
    for (const handler of this.modelHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
    return true;
  }

  private maybeApplyAgentMode(params: unknown): boolean {
    const obj = (params ?? {}) as { update?: unknown };
    const update = (obj.update ?? {}) as {
      sessionUpdate?: unknown;
      currentMode?: unknown;
      mode?: unknown;
    };
    if (update.sessionUpdate !== "current_mode_update") {
      return false;
    }
    const raw =
      typeof update.currentMode === "string"
        ? update.currentMode
        : typeof update.mode === "string"
        ? update.mode
        : undefined;
    if (raw === undefined) {
      return true;
    }
    const trimmed = raw.trim();
    if (!trimmed || trimmed === this.currentMode) {
      return true;
    }
    this.currentMode = trimmed;
    for (const handler of this.modeHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
    return true;
  }

  // Update the cached agent command list, fire persist handlers, and
  // broadcast the merged list to attached clients. Idempotent on a
  // structurally identical list so we don't churn meta.json on noisy
  // re-emissions.
  private setAgentAdvertisedCommands(commands: AdvertisedCommand[]): void {
    if (sameAdvertisedCommands(this.agentAdvertisedCommands, commands)) {
      // Still broadcast — a fresh attach might be racing — but skip
      // persistence to avoid pointless meta.json writes.
      this.broadcastMergedCommands();
      return;
    }
    this.agentAdvertisedCommands = commands;
    for (const handler of this.agentCommandsHandlers) {
      try {
        handler(commands);
      } catch {
        void 0;
      }
    }
    this.broadcastMergedCommands();
  }

  // Subscribe to snapshot-state updates. SessionManager wires these to
  // persist the new value into meta.json so cold resurrect can restore
  // them via the attach response _meta.
  onAgentCommandsChange(
    handler: (commands: AdvertisedCommand[]) => void,
  ): void {
    this.agentCommandsHandlers.push(handler);
  }

  onModelChange(handler: (model: string) => void): void {
    this.modelHandlers.push(handler);
  }

  onModeChange(handler: (mode: string) => void): void {
    this.modeHandlers.push(handler);
  }

  // Returns a freshly merged command list (hydra ∪ agent) for callers
  // that need a snapshot — notably acp-ws.ts's buildResponseMeta when
  // assembling the attach response.
  mergedAvailableCommands(): AdvertisedCommand[] {
    return [...hydraCommandsAsAdvertised(), ...this.agentAdvertisedCommands];
  }

  // Pick up an agent-emitted session_info_update and store its title
  // as our canonical record. The notification is also forwarded to
  // clients via the surrounding recordAndBroadcast call. Authoritative
  // — overrides our placeholder.
  private maybeApplyAgentSessionInfo(params: unknown): void {
    const obj = (params ?? {}) as { update?: unknown };
    const update = (obj.update ?? {}) as {
      sessionUpdate?: unknown;
      title?: unknown;
    };
    if (update.sessionUpdate !== "session_info_update") {
      return;
    }
    if (typeof update.title !== "string") {
      return;
    }
    const trimmed = update.title.trim();
    if (!trimmed || trimmed === this.title) {
      return;
    }
    this.title = trimmed;
    this.firstPromptSeeded = true;
    for (const handler of this.titleHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
  }

  // Dispatch a /hydra <verb> [args] slash command typed in any client's
  // composer. Returns a synthesized session/prompt response so the
  // caller's promise resolves like a normal turn. To add a verb: append
  // an entry to HYDRA_COMMANDS (drives validation + client advertising)
  // and a dispatch case in the switch below.
  private async handleSlashCommand(text: string): Promise<unknown> {
    const rest = text.slice("/hydra".length).trim();
    const match = rest.match(/^(\S+)(?:\s+([\s\S]*))?$/);
    const verb = match?.[1] ?? "";
    const arg = (match?.[2] ?? "").trim();
    if (verb === "") {
      // "/hydra" alone: no-op, return success so the user's
      // composer doesn't show an error.
      return { stopReason: "end_turn" };
    }
    if (!HYDRA_COMMANDS.some((c) => c.verb === verb)) {
      const known = HYDRA_COMMANDS.map((c) => c.verb).join(", ");
      const err = new Error(
        `unknown /hydra verb: ${verb} (known: ${known})`,
      ) as Error & { code: number };
      err.code = JsonRpcErrorCodes.InvalidParams;
      throw err;
    }
    switch (verb) {
      case "title":
        return this.runTitleCommand(arg);
      case "switch":
        return this.runSwitchCommand(arg);
      default: {
        // Listed in HYDRA_COMMANDS but no dispatch case — wired up wrong.
        const err = new Error(
          `no dispatcher for /hydra verb ${verb}`,
        ) as Error & { code: number };
        err.code = JsonRpcErrorCodes.InternalError;
        throw err;
      }
    }
  }

  // Runs as a normal queued prompt (so it serializes after any in-flight
  // turn). With an arg, sets the title directly. Without one, runs a
  // suppressed sub-prompt to the agent and uses its reply as the title.
  // Either path ends with setTitle, which broadcasts session_info_update
  // — that's what every other client observes.
  private runTitleCommand(arg: string): Promise<unknown> {
    return this.enqueuePrompt(async () => {
      if (arg) {
        this.setTitle(arg);
        return { stopReason: "end_turn" };
      }
      return this.runTitleRegen();
    });
  }

  private async runTitleRegen(): Promise<unknown> {
    const collected = await this.runInternalPrompt(
      "Reply with ONLY a short title (≤80 chars) summarizing this conversation so far. No quotes, no markdown, no explanation.",
    );
    const title = firstLine(collected.trim(), 80);
    if (title) {
      this.setTitle(title);
    }
    return { stopReason: "end_turn" };
  }

  // Send a prompt to the underlying agent and capture its reply chunks
  // privately (no fan-out to clients, no recording into history). Used
  // by /hydra title's regen path and /hydra switch's transcript-injection
  // path. Returns the joined agent_message_chunk text.
  private async runInternalPrompt(text: string): Promise<string> {
    if (this.internalPromptCapture) {
      throw new Error("internal prompt already in flight");
    }
    const capture: { chunks: string[] } = { chunks: [] };
    this.internalPromptCapture = capture;
    try {
      await this.agent.connection.request<unknown>("session/prompt", {
        sessionId: this.upstreamSessionId,
        prompt: [{ type: "text", text }],
      });
      return capture.chunks.join("");
    } finally {
      this.internalPromptCapture = undefined;
    }
  }

  // Swap the underlying agent process while keeping the same Session
  // record. Spawns the new agent first so a failure leaves the old one
  // intact; then injects a synthesized transcript so the new agent has
  // context for the next turn.
  private runSwitchCommand(newAgentId: string): Promise<unknown> {
    if (!newAgentId) {
      throw withCode(
        new Error("/hydra switch requires an agent id"),
        JsonRpcErrorCodes.InvalidParams,
      );
    }
    if (newAgentId === this.agentId) {
      throw withCode(
        new Error(`already on agent ${newAgentId}`),
        JsonRpcErrorCodes.InvalidParams,
      );
    }
    if (!this.spawnReplacementAgent) {
      throw withCode(
        new Error("agent switching not configured for this session"),
        JsonRpcErrorCodes.InternalError,
      );
    }
    const spawnAgent = this.spawnReplacementAgent;
    return this.enqueuePrompt(async () => {
      const oldAgentId = this.agentId;
      const transcript = this.buildSwitchTranscript(oldAgentId);

      const fresh = await spawnAgent({
        agentId: newAgentId,
        cwd: this.cwd,
        agentArgs: this.agentArgs,
      });
      this.wireAgent(fresh.agent);

      const oldAgent = this.agent;
      this.agent = fresh.agent;
      this.agentId = newAgentId;
      this.upstreamSessionId = fresh.upstreamSessionId;
      this.agentMeta = fresh.agentMeta;
      // Old agent's commands no longer apply; clear and re-broadcast
      // a merged update with just /hydra verbs until the new agent
      // advertises its own.
      this.agentAdvertisedCommands = [];
      this.broadcastMergedCommands();
      await oldAgent.kill().catch(() => undefined);

      if (transcript) {
        await this.runInternalPrompt(transcript).catch(() => undefined);
      }

      this.broadcastAgentSwitch(oldAgentId, newAgentId);

      const info = {
        agentId: this.agentId,
        upstreamSessionId: this.upstreamSessionId,
      };
      for (const handler of this.agentChangeHandlers) {
        try {
          handler(info);
        } catch {
          void 0;
        }
      }
      return { stopReason: "end_turn" };
    });
  }

  // Walk this.history (rewritten-for-clients notification cache) and
  // produce a labeled transcript suitable for handing to a fresh agent.
  // Includes user prompts, agent replies, and tool-call outcomes; skips
  // hydra-synthesized markers (so multi-hop switches don't accumulate
  // banners) and other update kinds we don't think the next agent
  // benefits from re-seeing (plans, thoughts, mode/model/usage).
  private buildSwitchTranscript(prevAgentId: string): string {
    const lines: Array<{ speaker: string; text: string }> = [];
    for (const note of this.history) {
      if (note.method !== "session/update") {
        continue;
      }
      const params = (note.params ?? {}) as { update?: Record<string, unknown> };
      const update = params.update;
      if (!update) {
        continue;
      }
      const meta = update._meta as
        | { "hydra-acp"?: { synthetic?: boolean } }
        | undefined;
      if (meta?.["hydra-acp"]?.synthetic) {
        continue;
      }
      const kind = update.sessionUpdate as string | undefined;
      if (kind === "prompt_received") {
        const text = extractPromptText(update.prompt);
        if (text) {
          lines.push({ speaker: "user", text });
        }
      } else if (kind === "agent_message_chunk") {
        const content = update.content as { text?: string } | undefined;
        const text = content?.text;
        if (text) {
          lines.push({ speaker: `agent: ${prevAgentId}`, text });
        }
      } else if (kind === "tool_call" || kind === "tool_call_update") {
        const status = update.status as string | undefined;
        const title = update.title as string | undefined;
        if (status === "completed" || status === "failed") {
          lines.push({
            speaker: "tool",
            text: `${title ?? "?"} ${status}`,
          });
        }
      }
    }
    if (lines.length === 0) {
      return "";
    }
    // Coalesce consecutive same-speaker entries (chunks → paragraph).
    const coalesced: string[] = [];
    let current: { speaker: string; text: string } | undefined;
    for (const line of lines) {
      if (current && current.speaker === line.speaker) {
        current.text += line.text;
      } else {
        if (current) {
          coalesced.push(`<${current.speaker}>: ${current.text.trim()}`);
        }
        current = { speaker: line.speaker, text: line.text };
      }
    }
    if (current) {
      coalesced.push(`<${current.speaker}>: ${current.text.trim()}`);
    }
    return [
      `You are taking over this conversation from ${prevAgentId}. Below is the transcript so far.`,
      `Each line is prefixed with its speaker. Continue from where ${prevAgentId} left off, responding to the user's most recent message.`,
      "",
      "--- begin transcript ---",
      ...coalesced,
      "--- end transcript ---",
    ].join("\n");
  }

  // Tell every attached client (a) the agent identity has changed
  // (session_info_update with an agentId field — clients that already
  // listen for title updates pick this up; older clients ignore unknown
  // fields harmlessly) and (b) drop a visible banner into the transcript
  // so users see the switch rather than just suddenly getting answers
  // from a different agent. Both updates carry _meta["hydra-acp"].synthetic
  // so a future /hydra switch's transcript builder filters them out.
  private broadcastAgentSwitch(oldAgentId: string, newAgentId: string): void {
    this.recordAndBroadcast("session/update", {
      sessionId: this.sessionId,
      update: {
        sessionUpdate: "session_info_update",
        agentId: newAgentId,
        _meta: { "hydra-acp": { synthetic: true } },
      },
    });
    this.recordAndBroadcast("session/update", {
      sessionId: this.sessionId,
      update: {
        sessionUpdate: "agent_message_chunk",
        content: {
          type: "text",
          text: `\n_(switched from \`${oldAgentId}\` to \`${newAgentId}\`)_\n`,
        },
        _meta: { "hydra-acp": { synthetic: true } },
      },
    });
  }

  private markClosed(opts: { deleteRecord: boolean }): void {
    if (this.closed) {
      return;
    }
    this.closed = true;
    this.cancelIdleTimer();
    for (const client of this.clients.values()) {
      void client.connection
        .notify("hydra-acp/session_closed", { sessionId: this.sessionId })
        .catch(() => undefined);
    }
    this.clients.clear();
    for (const handler of this.closeHandlers) {
      handler(opts);
    }
  }

  private maybeStartIdleTimer(): void {
    if (this.closed || this.clients.size > 0 || this.idleTimeoutMs <= 0) {
      return;
    }
    if (this.idleTimer) {
      return;
    }
    this.idleTimer = setTimeout(() => {
      this.idleTimer = undefined;
      // A session that never received a prompt has no conversation to
      // preserve; drop the record entirely instead of leaving an empty
      // cold session cluttering the picker. Otherwise persist as cold,
      // asking the agent for one last title summary on the way out.
      const opts: CloseOptions = this.firstPromptSeeded
        ? { deleteRecord: false, regenTitle: true }
        : { deleteRecord: true };
      void this.close(opts).catch(() => undefined);
    }, this.idleTimeoutMs);
    if (typeof this.idleTimer.unref === "function") {
      this.idleTimer.unref();
    }
  }

  private cancelIdleTimer(): void {
    if (this.idleTimer) {
      clearTimeout(this.idleTimer);
      this.idleTimer = undefined;
    }
  }

  private rewriteForClient(params: unknown): unknown {
    if (params && typeof params === "object" && !Array.isArray(params)) {
      const obj = params as Record<string, unknown>;
      if (obj.sessionId === this.upstreamSessionId) {
        return { ...obj, sessionId: this.sessionId };
      }
    }
    return params;
  }

  private recordAndBroadcast(
    method: string,
    params: unknown,
    excludeClientId?: string,
  ): void {
    const rewritten = this.rewriteForClient(params);
    // Snapshot-shaped updates (title, model, mode, available commands)
    // are broadcast live but deliberately not recorded. Their canonical
    // state lives in meta.json and is delivered to fresh clients via
    // the attach response _meta. Replaying historical transitions would
    // just churn client state through stale values en route to the
    // current one.
    const recordable = !isStateUpdate(method, rewritten);
    if (recordable) {
      const entry: CachedNotification = {
        method,
        params: rewritten,
        recordedAt: Date.now(),
      };
      this.history.push(entry);
      let trimmed = false;
      if (this.history.length > 1000) {
        this.history = this.history.slice(-500);
        trimmed = true;
      }
      // Mirror the in-memory cache to disk so a session that goes cold
      // still has its replay buffer available on resurrect. The append
      // path is fire-and-forget; failures (full disk, permission
      // problems) shouldn't block the live broadcast. On trim we
      // rewrite the full window so the file stays bounded by the same
      // cap.
      if (this.historyStore) {
        if (trimmed) {
          void this.historyStore
            .rewrite(this.sessionId, [...this.history])
            .catch(() => undefined);
        } else {
          void this.historyStore.append(this.sessionId, entry).catch(
            () => undefined,
          );
        }
      }
      // Fan the recorded entry out to any tail-style subscribers
      // (currently the HTTP /history?follow=1 stream). Synchronous
      // dispatch so a subscriber sees the entry in order; handlers
      // own their own error handling.
      for (const handler of this.broadcastHandlers) {
        try {
          handler(entry);
        } catch {
          void 0;
        }
      }
    }
    this.updatedAt = Date.now();
    for (const client of this.clients.values()) {
      if (excludeClientId && client.clientId === excludeClientId) {
        continue;
      }
      void client.connection.notify(method, rewritten).catch(() => undefined);
    }
  }

  private async handlePermissionRequest(params: unknown): Promise<unknown> {
    const initialClients = [...this.clients.values()];
    if (initialClients.length === 0) {
      throw withCode(
        new Error("no clients attached to handle permission request"),
        JsonRpcErrorCodes.PermissionDenied,
      );
    }
    const clientParams = this.rewriteForClient(params);
    return new Promise<unknown>((resolve, reject) => {
      let settled = false;
      // Track each outbound request id so the resolved-sibling notification
      // can carry the recipient's *own* id — that's the key the slack/browser
      // clients (and the shim's pendingPermissions tracker) match against.
      const outbound: Array<{ client: AttachedClient; id: JsonRpcId }> = [];
      // The Set entry is what attach() consults; storing it ahead of time
      // lets the settle path delete by identity.
      const entry = { addClient: sendTo };
      this.inFlightPermissions.add(entry);

      const settle = (fn: () => void): void => {
        if (settled) {
          return;
        }
        settled = true;
        this.inFlightPermissions.delete(entry);
        fn();
      };

      function sendTo(client: AttachedClient): void {
        if (settled) {
          return;
        }
        const { id, response } = client.connection.requestWithId(
          "session/request_permission",
          clientParams,
        );
        outbound.push({ client, id });
        void response
          .then((result) => {
            settle(() => {
              for (const o of outbound) {
                if (o.client.clientId === client.clientId) {
                  continue;
                }
                void o.client.connection
                  .notify("session/permission_resolved", {
                    ...(clientParams as object),
                    requestId: o.id,
                    resolvedBy: client.clientId,
                    result,
                  })
                  .catch(() => undefined);
              }
              resolve(result);
            });
          })
          .catch((err) => {
            settle(() => reject(err));
          });
      }

      for (const client of initialClients) {
        sendTo(client);
      }
    });
  }

  private async enqueuePrompt(task: () => Promise<unknown>): Promise<unknown> {
    return new Promise<unknown>((resolve, reject) => {
      const run = async (): Promise<void> => {
        try {
          const result = await task();
          resolve(result);
        } catch (err) {
          reject(err as Error);
        }
      };
      this.promptQueue.push(run);
      void this.drainQueue();
    });
  }

  private async drainQueue(): Promise<void> {
    if (this.promptInFlight) {
      return;
    }
    this.promptInFlight = true;
    try {
      while (this.promptQueue.length > 0) {
        const next = this.promptQueue.shift();
        if (next) {
          await next();
        }
      }
    } finally {
      this.promptInFlight = false;
    }
  }
}

function withCode(err: Error, code: number): Error & { code: number } {
  (err as Error & { code: number }).code = code;
  return err as Error & { code: number };
}

// session/update kinds that carry "what's currently true" snapshots
// rather than conversation events. Broadcast live but not recorded to
// history — the canonical state lives in meta.json and is delivered to
// fresh attaches via the attach response _meta.
const STATE_UPDATE_KINDS = new Set([
  "session_info_update",
  "current_model_update",
  "current_mode_update",
  "available_commands_update",
]);

function isStateUpdate(method: string, params: unknown): boolean {
  if (method !== "session/update") {
    return false;
  }
  const obj = (params ?? {}) as { update?: { sessionUpdate?: unknown } };
  const kind = obj.update?.sessionUpdate;
  return typeof kind === "string" && STATE_UPDATE_KINDS.has(kind);
}

function sameAdvertisedCommands(
  a: AdvertisedCommand[],
  b: AdvertisedCommand[],
): boolean {
  if (a.length !== b.length) {
    return false;
  }
  for (let i = 0; i < a.length; i++) {
    if (a[i]?.name !== b[i]?.name || a[i]?.description !== b[i]?.description) {
      return false;
    }
  }
  return true;
}

// Pull text out of an agent_message_chunk session/update notification
// and append it to a /hydra-slash-command's private capture buffer.
// Other update kinds (thoughts, tool calls, plans, etc.) are swallowed
// — we only need the prose reply.
function captureInternalChunk(
  capture: { chunks: string[] },
  params: unknown,
): void {
  const obj = (params ?? {}) as { update?: unknown };
  const update = (obj.update ?? {}) as {
    sessionUpdate?: unknown;
    content?: unknown;
  };
  if (update.sessionUpdate !== "agent_message_chunk") {
    return;
  }
  const content = (update.content ?? {}) as { text?: unknown };
  if (typeof content.text === "string") {
    capture.chunks.push(content.text);
  }
}

// Returns the agent-advertised command list when params is a session/update
// of kind available_commands_update; null otherwise. Used to intercept the
// agent's raw update so we can re-emit a merged (hydra ∪ agent) version
// to clients via broadcastMergedCommands.
function extractAdvertisedCommands(
  params: unknown,
): AdvertisedCommand[] | null {
  const obj = (params ?? {}) as { update?: unknown };
  const update = (obj.update ?? {}) as {
    sessionUpdate?: unknown;
    availableCommands?: unknown;
    commands?: unknown;
  };
  if (update.sessionUpdate !== "available_commands_update") {
    return null;
  }
  const list = update.availableCommands ?? update.commands;
  if (!Array.isArray(list)) {
    return [];
  }
  const out: AdvertisedCommand[] = [];
  for (const raw of list) {
    if (!raw || typeof raw !== "object") {
      continue;
    }
    const c = raw as { name?: unknown; description?: unknown };
    if (typeof c.name !== "string" || c.name.length === 0) {
      continue;
    }
    const cmd: AdvertisedCommand = { name: c.name };
    if (typeof c.description === "string") {
      cmd.description = c.description;
    }
    out.push(cmd);
  }
  return out;
}

function extractPromptText(prompt: unknown): string {
  if (typeof prompt === "string") {
    return prompt;
  }
  if (!Array.isArray(prompt)) {
    return "";
  }
  return prompt
    .map((b) => {
      if (b && typeof b === "object" && typeof (b as { text?: unknown }).text === "string") {
        return (b as { text: string }).text;
      }
      return "";
    })
    .join("");
}

// First non-empty line of `text`, truncated to `max` chars with a
// trailing ellipsis if needed. Used to seed a session title from the
// first user prompt's leading line.
function firstLine(text: string, max: number): string | undefined {
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) {
      continue;
    }
    return line.length > max ? `${line.slice(0, max)}…` : line;
  }
  return undefined;
}
