import { customAlphabet } from "nanoid";

// nanoid's default alphabet is URL-safe (alphanumerics + `-` + `_`). We
// drop both punctuation chars: `-` collides with parsers that treat dashes
// as field separators, and `_` looks doubled against the literal prefix
// (`hydra_session__foo`). Plain alphanumeric is plenty of entropy at
// length 16 (~95 bits).
const HYDRA_ID_ALPHABET =
  "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
const generateHydraId = customAlphabet(HYDRA_ID_ALPHABET, 16);

export const HYDRA_SESSION_PREFIX = "hydra_session_";

// Stable id stamped onto prompt_received / turn_complete updates per
// RFD #533. Lets reconnecting clients pass `after_message: <id>` to
// resync only the delta. 16 chars of alphanumeric is ~95 bits — plenty.
function generateMessageId(): string {
  return `m_${generateHydraId()}`;
}

// Display helper: strip the constant prefix from auto-generated session ids
// so the random tail is what users see in lists and pickers. Foreign ids
// (anything not generated by us) pass through untouched.
export function stripHydraSessionPrefix(id: string): string {
  return id.startsWith(HYDRA_SESSION_PREFIX)
    ? id.slice(HYDRA_SESSION_PREFIX.length)
    : id;
}
import { AgentInstance } from "./agent-instance.js";
import {
  HYDRA_COMMANDS,
  hydraCommandsAsAdvertised,
  type AdvertisedCommand,
} from "./hydra-commands.js";
import type { HistoryEntry, HistoryStore } from "./history-store.js";
import type { JsonRpcConnection } from "../acp/connection.js";
import type { HistoryPolicy } from "../acp/types.js";
import { JsonRpcErrorCodes } from "../acp/types.js";

export interface AttachedClient {
  clientId: string;
  connection: JsonRpcConnection;
  clientInfo?: { name: string; version?: string };
}

export type CachedNotification = HistoryEntry;

export interface SpawnReplacementAgentParams {
  agentId: string;
  cwd: string;
  agentArgs?: string[];
}

export interface SpawnReplacementAgentResult {
  agent: AgentInstance;
  upstreamSessionId: string;
  agentMeta?: Record<string, unknown>;
}

export type SpawnReplacementAgent = (
  params: SpawnReplacementAgentParams,
) => Promise<SpawnReplacementAgentResult>;

// Snapshot of the most recent usage_update notification: tokens used,
// context size, and cost. Fields are individually optional so a fresh
// event can update only what it carries while preserving prior values
// for everything else.
export interface UsageSnapshot {
  used?: number;
  size?: number;
  costAmount?: number;
  costCurrency?: string;
}

export interface SessionInit {
  cwd: string;
  agentId: string;
  agent: AgentInstance;
  upstreamSessionId: string;
  title?: string;
  sessionId?: string;
  agentMeta?: Record<string, unknown>;
  agentArgs?: string[];
  idleTimeoutMs?: number;
  // Pino-style logger for close + idle paths. Optional so tests/consumers
  // that construct Session directly aren't forced to provide one.
  logger?: { info: (msg: string) => void; warn: (msg: string) => void };
  // Optional callback used by /hydra agent to spawn a fresh agent
  // process and run initialize + session/new on it. Provided by
  // SessionManager so Session doesn't have to depend on the registry.
  spawnReplacementAgent?: SpawnReplacementAgent;
  // Every recordAndBroadcast entry is persisted here. attach()/getHistorySnapshot()
  // load from this store on demand — Session keeps no in-memory copy.
  historyStore?: HistoryStore;
  // Cap on entries retained in the on-disk history.jsonl. The compaction
  // trigger is derived as 20% of this value (min 1), so larger caps also
  // compact less often. Defaults to 1000 if omitted.
  historyMaxEntries?: number;
  // Snapshot state restored from meta.json on cold resurrect, so the
  // first attach response can deliver the right model/mode/commands
  // via _meta before the agent re-emits.
  currentModel?: string;
  currentMode?: string;
  currentUsage?: UsageSnapshot;
  agentCommands?: AdvertisedCommand[];
  // Suppress the first-prompt title heuristic. Set by SessionManager
  // when resurrecting a session whose title is already meaningful (from
  // a prior life's prompt seed, /hydra title, or regenTitle) — without
  // this, the next prompt would clobber the persisted title.
  firstPromptSeeded?: boolean;
  createdAt?: number;
}

export interface CloseOptions {
  deleteRecord?: boolean;
  // Before tearing the agent down, ask it for a fresh title that
  // summarises the conversation so far. Used by the idle-timeout path so
  // a session going cold persists a meaningful title for the picker.
  // Best-effort: failures are swallowed and the close proceeds.
  regenTitle?: boolean;
  // Maximum time to wait for the title regen before giving up and
  // killing the agent anyway. Defaults to 5 seconds.
  regenTitleTimeoutMs?: number;
}

const DEFAULT_HISTORY_MAX_ENTRIES = 1000;

export class Session {
  readonly sessionId: string;
  readonly cwd: string;
  // agent / agentId / upstreamSessionId are mutable so /hydra agent can
  // replace the underlying agent process while keeping the same Session
  // record. agentMeta is the metadata returned by the agent at session/new
  // time; it gets refreshed on switch too.
  agentId: string;
  agent: AgentInstance;
  upstreamSessionId: string;
  agentMeta: Record<string, unknown> | undefined;
  readonly agentArgs: string[] | undefined;
  title: string | undefined;
  // Snapshot state delivered to attaching clients via the attach
  // response _meta rather than via history replay (which would be
  // stale-prone for snapshot-shaped events).
  currentModel: string | undefined;
  currentMode: string | undefined;
  currentUsage: UsageSnapshot | undefined;
  updatedAt: number;
  readonly createdAt: number;

  private clients = new Map<string, AttachedClient>();
  private historyStore: HistoryStore | undefined;
  private promptQueue: Array<() => Promise<void>> = [];
  private promptInFlight = false;
  private closed = false;
  private closeHandlers: Array<(opts: { deleteRecord: boolean }) => void> = [];
  private titleHandlers: Array<(title: string) => void> = [];
  // Subscribers notified after every entry that's actually persisted to
  // history (skipping snapshot-shaped events filtered by
  // recordAndBroadcast). The HTTP /v1/sessions/:id/history?follow=1
  // endpoint uses this to tail a live session's conversation stream
  // without participating in turns or prompts.
  private broadcastHandlers: Array<(entry: CachedNotification) => void> = [];
  // True once we've observed our first session/prompt; gates the
  // first-prompt-seeded title so subsequent prompts don't churn it.
  private firstPromptSeeded = false;
  // Wall-clock when the active prompt started, undefined when idle.
  // Bumped by broadcastPromptReceived, cleared by broadcastTurnComplete.
  // Drives the mid-turn elapsed counter delivered to fresh attachers.
  private promptStartedAt: number | undefined;
  // Counts appends since the last compaction. When it hits compactEvery
  // we ask the history store to trim the file to the most recent
  // historyMaxEntries. Keeps file growth bounded without per-append
  // file-size checks.
  private appendCount = 0;
  private historyMaxEntries: number;
  private compactEvery: number;
  // Permission requests that have been broadcast to one or more
  // clients but have not yet resolved. Replayed to clients that
  // attach mid-flight so a late joiner sees the prompt instead of an
  // empty session waiting on something they can't see. Settled entries
  // are removed so this map only ever contains live requests.
  private inFlightPermissions = new Set<{
    addClient: (client: AttachedClient) => void;
  }>();
  // While set, agent-emitted session/update notifications are
  // captured into `chunks` and NOT broadcast to clients. Used by
  // /hydra slash-command sub-prompts (e.g. title regeneration) so
  // the conversation log doesn't get polluted with the meta-prompt
  // and its reply.
  private internalPromptCapture: { chunks: string[] } | undefined;
  private idleTimeoutMs: number;
  private idleTimer: NodeJS.Timeout | undefined;
  // Time of the last recordable broadcast (or session creation, if
  // none yet). Drives the inactivity-based idle close; deliberately
  // does NOT include snapshot state pings (model/mode/title/commands)
  // or attach/detach, which would otherwise let passive observers
  // and noisy state churn keep a quiet session alive forever.
  private lastRecordedAt: number;
  private spawnReplacementAgent: SpawnReplacementAgent | undefined;
  private logger: SessionInit["logger"];
  private agentChangeHandlers: Array<
    (info: { agentId: string; upstreamSessionId: string }) => void
  > = [];
  // Last available_commands_update we observed from the agent. Stored
  // so we can re-broadcast a merged (hydra ∪ agent) list whenever
  // either half changes, and persisted to meta.json so a fresh attach
  // can deliver the merged list via _meta without depending on history
  // replay.
  private agentAdvertisedCommands: AdvertisedCommand[] = [];
  // Persist hooks for snapshot-shaped state. SessionManager hooks these
  // to mirror changes into meta.json so cold-resurrect attaches can
  // surface the latest snapshot via the attach response _meta.
  private agentCommandsHandlers: Array<
    (commands: AdvertisedCommand[]) => void
  > = [];
  private modelHandlers: Array<(model: string) => void> = [];
  private modeHandlers: Array<(mode: string) => void> = [];
  private usageHandlers: Array<(usage: UsageSnapshot) => void> = [];

  constructor(init: SessionInit) {
    this.sessionId =
      init.sessionId ?? `${HYDRA_SESSION_PREFIX}${generateHydraId()}`;
    this.cwd = init.cwd;
    this.agentId = init.agentId;
    this.agent = init.agent;
    this.upstreamSessionId = init.upstreamSessionId;
    this.agentMeta = init.agentMeta;
    this.agentArgs = init.agentArgs;
    this.title = init.title;
    this.currentModel = init.currentModel;
    this.currentMode = init.currentMode;
    this.currentUsage = init.currentUsage;
    if (init.agentCommands && init.agentCommands.length > 0) {
      this.agentAdvertisedCommands = [...init.agentCommands];
    }
    this.idleTimeoutMs = init.idleTimeoutMs ?? 0;
    this.spawnReplacementAgent = init.spawnReplacementAgent;
    this.logger = init.logger;
    if (init.firstPromptSeeded) {
      this.firstPromptSeeded = true;
    }
    this.historyStore = init.historyStore;
    this.historyMaxEntries = init.historyMaxEntries ?? DEFAULT_HISTORY_MAX_ENTRIES;
    this.compactEvery = Math.max(1, Math.floor(this.historyMaxEntries * 0.2));
    this.updatedAt = Date.now();
    this.createdAt = init.createdAt ?? this.updatedAt;
    // Resurrection itself is the activity that gets a fresh idle
    // window — even if the disk history is hours old, the user
    // attaching now is current activity.
    this.lastRecordedAt = this.updatedAt;

    this.wireAgent(this.agent);
    this.scheduleIdleCheck();
  }

  private broadcastMergedCommands(): void {
    const merged: AdvertisedCommand[] = [
      ...hydraCommandsAsAdvertised(),
      ...this.agentAdvertisedCommands,
    ];
    this.recordAndBroadcast("session/update", {
      sessionId: this.upstreamSessionId,
      update: {
        sessionUpdate: "available_commands_update",
        availableCommands: merged,
      },
    });
  }

  // Register session/update, session/request_permission, and onExit
  // handlers on an agent connection. Re-run on every /hydra agent so
  // the new agent is plumbed identically. The exit handler's identity
  // check is what makes switching safe: when the *old* agent exits as
  // part of a swap, this.agent has already been replaced, so we no-op
  // and don't tear the session down.
  private wireAgent(agent: AgentInstance): void {
    agent.connection.onNotification("session/update", (params) => {
      // /hydra slash-command sub-prompts (e.g. title regeneration)
      // run "behind the scenes" — the agent's chunks for those are
      // captured into a private buffer instead of being broadcast.
      if (this.internalPromptCapture) {
        captureInternalChunk(this.internalPromptCapture, params);
        return;
      }
      // available_commands_update is intercepted: cache the agent's
      // list, persist to meta.json (so resurrect can deliver via _meta),
      // and re-emit a merged (hydra ∪ agent) version live. The merged
      // broadcast itself is filtered from history persistence by
      // recordAndBroadcast — clients learn the current commands either
      // live or via attach response _meta.
      const agentCmds = extractAdvertisedCommands(params);
      if (agentCmds !== null) {
        this.setAgentAdvertisedCommands(agentCmds);
        return;
      }
      // current_model_update / current_mode_update are similarly
      // snapshot-shaped: cache, persist, broadcast (but filtered from
      // history). The broadcast still fires so live clients see the
      // change immediately; new attaches get it via _meta.
      if (this.maybeApplyAgentModel(params)) {
        this.recordAndBroadcast("session/update", params);
        return;
      }
      if (this.maybeApplyAgentMode(params)) {
        this.recordAndBroadcast("session/update", params);
        return;
      }
      // usage_update: snapshot-shaped like model/mode. Merge into
      // currentUsage, fire usage handlers (SessionManager persists to
      // meta.json so cold resurrect can rehydrate), then broadcast.
      // recordAndBroadcast filters usage_update out of history.
      if (this.maybeApplyAgentUsage(params)) {
        this.recordAndBroadcast("session/update", params);
        return;
      }
      // Pick up agent-emitted session_info_update so the canonical
      // title in this Session matches what clients see broadcast.
      // Forwarded as-is through recordAndBroadcast below.
      this.maybeApplyAgentSessionInfo(params);
      this.recordAndBroadcast("session/update", params);
    });
    agent.connection.onRequest("session/request_permission", async (params) => {
      return this.handlePermissionRequest(params);
    });
    agent.onExit(() => {
      if (this.agent !== agent) {
        return;
      }
      this.markClosed({ deleteRecord: false });
    });
  }

  onAgentChange(
    handler: (info: { agentId: string; upstreamSessionId: string }) => void,
  ): void {
    this.agentChangeHandlers.push(handler);
  }

  get attachedCount(): number {
    return this.clients.size;
  }

  // Roster of currently-attached clients, optionally excluding one
  // clientId. Used by the daemon to populate connectedClients on the
  // session/attach response (per RFD #533) — the freshly-attaching
  // client wants to see who else is on the session but not itself in
  // the list.
  connectedClients(
    excludeClientId?: string,
  ): Array<{ clientId: string; name?: string; version?: string }> {
    const out: Array<{ clientId: string; name?: string; version?: string }> = [];
    for (const client of this.clients.values()) {
      if (excludeClientId && client.clientId === excludeClientId) {
        continue;
      }
      const entry: { clientId: string; name?: string; version?: string } = {
        clientId: client.clientId,
      };
      if (client.clientInfo?.name) {
        entry.name = client.clientInfo.name;
      }
      if (client.clientInfo?.version) {
        entry.version = client.clientInfo.version;
      }
      out.push(entry);
    }
    return out;
  }

  // Wall-clock when the in-flight agent turn began, or undefined when
  // idle. Tracked in-memory by broadcastPromptReceived/broadcastTurnComplete
  // so the daemon can hand a fresh attacher mid-turn the right elapsed
  // time without scanning history.
  get turnStartedAt(): number | undefined {
    return this.promptStartedAt;
  }

  // Read the persisted history from disk. Returns [] if no history
  // file exists (fresh session, never prompted). Used by attach() and
  // the HTTP /history endpoint.
  async getHistorySnapshot(): Promise<CachedNotification[]> {
    if (!this.historyStore) {
      return [];
    }
    return this.historyStore.load(this.sessionId).catch(() => []);
  }

  // Subscribe to recordable broadcast entries — fires once per entry
  // that lands in history (so snapshot-shaped session_info/model/mode/
  // available_commands updates do NOT trigger this; they're broadcast
  // live but not recorded). Returns an unsubscribe function the caller
  // must invoke when done.
  onBroadcast(handler: (entry: CachedNotification) => void): () => void {
    this.broadcastHandlers.push(handler);
    return () => {
      const i = this.broadcastHandlers.indexOf(handler);
      if (i >= 0) {
        this.broadcastHandlers.splice(i, 1);
      }
    };
  }

  // Register a client and (asynchronously) load the replay slice it
  // should receive. Returns both the slice to replay and the actual
  // historyPolicy applied (which may differ from the requested one
  // when after_message falls back to full). Validation errors throw
  // synchronously so callers can rely on either the registration being
  // in effect or having thrown; the disk-load is the only async work.
  attach(
    client: AttachedClient,
    historyPolicy: HistoryPolicy,
    opts: { afterMessageId?: string } = {},
  ): Promise<{ entries: CachedNotification[]; appliedPolicy: HistoryPolicy }> {
    if (this.closed) {
      throw withCode(
        new Error("session is closed"),
        JsonRpcErrorCodes.SessionNotFound,
      );
    }
    if (this.clients.has(client.clientId)) {
      throw withCode(
        new Error(`client ${client.clientId} is already attached`),
        JsonRpcErrorCodes.AlreadyAttached,
      );
    }
    this.clients.set(client.clientId, client);
    this.updatedAt = Date.now();
    if (historyPolicy === "none" || historyPolicy === "pending_only") {
      return Promise.resolve({ entries: [], appliedPolicy: historyPolicy });
    }
    return this.loadReplay(historyPolicy, opts);
  }

  private async loadReplay(
    historyPolicy: HistoryPolicy,
    opts: { afterMessageId?: string },
  ): Promise<{ entries: CachedNotification[]; appliedPolicy: HistoryPolicy }> {
    const all = await this.getHistorySnapshot();
    if (historyPolicy === "after_message") {
      const cutoff = opts.afterMessageId
        ? findMessageIdIndex(all, opts.afterMessageId)
        : -1;
      if (cutoff < 0) {
        return { entries: all, appliedPolicy: "full" };
      }
      return { entries: all.slice(cutoff + 1), appliedPolicy: "after_message" };
    }
    return { entries: all, appliedPolicy: "full" };
  }

  // Dispatch in-flight permission requests to a freshly-attached
  // client. Called by the daemon's WS handler *after* it finishes
  // replaying history, so the prompt lands at the bottom of the
  // transcript rather than above the conversation.
  replayPendingPermissions(client: AttachedClient): void {
    for (const pending of this.inFlightPermissions) {
      pending.addClient(client);
    }
  }

  detach(clientId: string): void {
    const leaving = this.clients.get(clientId);
    if (!leaving) {
      return;
    }
    this.clients.delete(clientId);
    this.updatedAt = Date.now();
    this.broadcastClientDisconnected(leaving);
  }

  // Notify remaining attached clients that a peer just left, per
  // RFD #533. Fires for both explicit session/detach and ws-close
  // teardown (acp-ws calls Session.detach() in both paths). The
  // notification is broadcast (not recorded) — peer presence is
  // transient, not part of conversation history.
  private broadcastClientDisconnected(client: AttachedClient): void {
    const info: { clientId: string; name?: string; version?: string } = {
      clientId: client.clientId,
    };
    if (client.clientInfo?.name) {
      info.name = client.clientInfo.name;
    }
    if (client.clientInfo?.version) {
      info.version = client.clientInfo.version;
    }
    const update = {
      sessionUpdate: "client_disconnected",
      client: info,
      timestamp: new Date().toISOString(),
    };
    for (const peer of this.clients.values()) {
      void peer.connection
        .notify("session/update", {
          sessionId: this.sessionId,
          update,
        })
        .catch(() => undefined);
    }
  }

  async prompt(clientId: string, params: unknown): Promise<unknown> {
    const client = this.clients.get(clientId);
    if (!client) {
      throw withCode(
        new Error("client not attached"),
        JsonRpcErrorCodes.SessionNotFound,
      );
    }
    // Slash commands (e.g. "/hydra title", "/hydra title some name")
    // are intercepted before any broadcasting or first-prompt seeding.
    // They never reach the agent as a normal turn — hydra dispatches
    // them, optionally runs a side-channel sub-prompt, and emits
    // whatever notifications the verb implies (e.g. session_info_update
    // for /hydra title). The conversation log stays clean.
    const promptText = extractPromptText(
      ((params ?? {}) as { prompt?: unknown }).prompt,
    ).trim();
    if (promptText.startsWith("/hydra")) {
      return this.handleSlashCommand(promptText);
    }
    this.broadcastPromptReceived(client, params);
    this.maybeSeedTitleFromPrompt(params);
    return this.enqueuePrompt(async () => {
      // We always pair broadcastPromptReceived with a broadcastTurnComplete,
      // even when the agent request throws. The recorded history is what
      // late-joining clients replay on attach — leaving prompts unmatched
      // means the next turn's keyed blocks anchor mid-scrollback (the
      // TUI freezes them as "thought · Xs" but never closes the
      // logical turn). A synthetic stopReason here surfaces the failure
      // to history without burying the trail.
      let response: unknown;
      try {
        response = await this.agent.connection.request<unknown>(
          "session/prompt",
          {
            ...(params as object),
            sessionId: this.upstreamSessionId,
          },
        );
      } catch (err) {
        this.broadcastTurnComplete(client.clientId, { stopReason: "error" });
        throw err;
      }
      this.broadcastTurnComplete(client.clientId, response);
      return response;
    });
  }

  private broadcastPromptReceived(
    client: AttachedClient,
    params: unknown,
  ): void {
    const promptParams = (params ?? {}) as Record<string, unknown>;
    const sentBy: Record<string, unknown> = { clientId: client.clientId };
    if (client.clientInfo?.name) {
      sentBy.name = client.clientInfo.name;
    }
    if (client.clientInfo?.version) {
      sentBy.version = client.clientInfo.version;
    }
    this.promptStartedAt = Date.now();
    this.recordAndBroadcast(
      "session/update",
      {
        sessionId: this.sessionId,
        update: {
          sessionUpdate: "prompt_received",
          messageId: generateMessageId(),
          prompt: promptParams.prompt,
          sentBy,
        },
      },
      client.clientId,
    );

    // Compat shim for clients that don't yet implement RFD #533's
    // prompt_received. The marker in _meta lets prompt_received-aware
    // clients short-circuit this duplicate.
    const text = extractPromptText(promptParams.prompt);
    if (text.length > 0) {
      this.recordAndBroadcast(
        "session/update",
        {
          sessionId: this.sessionId,
          update: {
            sessionUpdate: "user_message_chunk",
            content: { type: "text", text },
            _meta: { "hydra-acp": { compatFor: "prompt_received" } },
          },
        },
        client.clientId,
      );
    }
  }

  private broadcastTurnComplete(
    originatorClientId: string,
    response: unknown,
  ): void {
    const stopReason =
      response &&
      typeof response === "object" &&
      "stopReason" in response &&
      typeof (response as { stopReason: unknown }).stopReason === "string"
        ? (response as { stopReason: string }).stopReason
        : undefined;
    const update: Record<string, unknown> = {
      sessionUpdate: "turn_complete",
      messageId: generateMessageId(),
    };
    if (stopReason !== undefined) {
      update.stopReason = stopReason;
    }
    this.promptStartedAt = undefined;
    this.recordAndBroadcast(
      "session/update",
      {
        sessionId: this.sessionId,
        update,
      },
      originatorClientId,
    );
  }

  async cancel(clientId: string): Promise<void> {
    const client = this.clients.get(clientId);
    if (!client) {
      throw withCode(
        new Error("client not attached"),
        JsonRpcErrorCodes.SessionNotFound,
      );
    }
    // session/cancel is a notification per the ACP spec — agents process it
    // and don't reply. Sending it as a request would hang our promise
    // forever waiting for a response that never comes.
    await this.agent.connection.notify("session/cancel", {
      sessionId: this.upstreamSessionId,
    });
  }

  async forwardRequest(method: string, params: unknown): Promise<unknown> {
    return this.agent.connection.request(method, this.rewriteForAgent(params));
  }

  private rewriteForAgent(params: unknown): unknown {
    if (params && typeof params === "object" && !Array.isArray(params)) {
      const obj = params as Record<string, unknown>;
      if (obj.sessionId === this.sessionId) {
        return { ...obj, sessionId: this.upstreamSessionId };
      }
    }
    return params;
  }

  async close(opts: CloseOptions = {}): Promise<void> {
    if (this.closed) {
      return;
    }
    this.logger?.info(
      `session ${this.sessionId} closing deleteRecord=${opts.deleteRecord ?? false} regenTitle=${opts.regenTitle ?? false}`,
    );
    this.cancelIdleTimer();
    if (opts.regenTitle && this.firstPromptSeeded) {
      const timeoutMs = opts.regenTitleTimeoutMs ?? 5000;
      await Promise.race([
        this.runTitleRegen().catch(() => undefined),
        new Promise<void>((r) => setTimeout(r, timeoutMs).unref?.()),
      ]);
    }
    await this.agent.kill().catch(() => undefined);
    this.markClosed({ deleteRecord: opts.deleteRecord ?? false });
  }

  onClose(handler: (opts: { deleteRecord: boolean }) => void): void {
    this.closeHandlers.push(handler);
  }

  // Subscribe to title updates. The SessionManager hooks this to
  // persist the new title to disk so a daemon restart restores it.
  onTitleChange(handler: (title: string) => void): void {
    this.titleHandlers.push(handler);
  }

  // Update the canonical title and broadcast a session_info_update to
  // every attached client. Clients that already speak the spec's
  // session_info_update need no hydra-specific wiring to pick this up.
  // Idempotent on identical values.
  private setTitle(title: string): void {
    const trimmed = title.trim();
    if (!trimmed || trimmed === this.title) {
      return;
    }
    this.title = trimmed;
    this.recordAndBroadcast("session/update", {
      sessionId: this.sessionId,
      update: {
        sessionUpdate: "session_info_update",
        title: trimmed,
        updatedAt: new Date().toISOString(),
      },
    });
    for (const handler of this.titleHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
  }

  // First-prompt heuristic: derive a session title from the first
  // session/prompt's text. Replaces whatever was set at session/new
  // (typically an editor frame name like "Claude Agent @ hydra-acp")
  // — the first prompt is a better summary for cross-client display
  // than the editor's static frame label. Subsequent prompts don't
  // touch the title; that'd flap as conversations evolved.
  private maybeSeedTitleFromPrompt(params: unknown): void {
    if (this.firstPromptSeeded) {
      return;
    }
    const promptParams = (params ?? {}) as { prompt?: unknown };
    const text = extractPromptText(promptParams.prompt);
    const seed = firstLine(text, 200);
    if (!seed) {
      return;
    }
    this.firstPromptSeeded = true;
    this.setTitle(seed);
  }

  // Apply an agent-emitted current_model_update. Returns true if the
  // notification was a model update (caller still needs to broadcast
  // it). Returns false otherwise so the caller can try the next kind.
  private maybeApplyAgentModel(params: unknown): boolean {
    const obj = (params ?? {}) as { update?: unknown };
    const update = (obj.update ?? {}) as {
      sessionUpdate?: unknown;
      currentModel?: unknown;
      model?: unknown;
    };
    if (update.sessionUpdate !== "current_model_update") {
      return false;
    }
    const raw =
      typeof update.currentModel === "string"
        ? update.currentModel
        : typeof update.model === "string"
        ? update.model
        : undefined;
    if (raw === undefined) {
      return true;
    }
    const trimmed = raw.trim();
    if (!trimmed || trimmed === this.currentModel) {
      return true;
    }
    this.currentModel = trimmed;
    for (const handler of this.modelHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
    return true;
  }

  private maybeApplyAgentMode(params: unknown): boolean {
    const obj = (params ?? {}) as { update?: unknown };
    const update = (obj.update ?? {}) as {
      sessionUpdate?: unknown;
      currentMode?: unknown;
      mode?: unknown;
    };
    if (update.sessionUpdate !== "current_mode_update") {
      return false;
    }
    const raw =
      typeof update.currentMode === "string"
        ? update.currentMode
        : typeof update.mode === "string"
        ? update.mode
        : undefined;
    if (raw === undefined) {
      return true;
    }
    const trimmed = raw.trim();
    if (!trimmed || trimmed === this.currentMode) {
      return true;
    }
    this.currentMode = trimmed;
    for (const handler of this.modeHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
    return true;
  }

  // usage_update carries any subset of {used, size, cost.amount,
  // cost.currency}. Merge non-undefined fields onto currentUsage so a
  // sparse update preserves prior values, and fire usage handlers only
  // if something actually changed.
  private maybeApplyAgentUsage(params: unknown): boolean {
    const obj = (params ?? {}) as { update?: unknown };
    const update = (obj.update ?? {}) as {
      sessionUpdate?: unknown;
      used?: unknown;
      size?: unknown;
      cost?: unknown;
    };
    if (update.sessionUpdate !== "usage_update") {
      return false;
    }
    const next: UsageSnapshot = { ...(this.currentUsage ?? {}) };
    let changed = false;
    if (typeof update.used === "number" && next.used !== update.used) {
      next.used = update.used;
      changed = true;
    }
    if (typeof update.size === "number" && next.size !== update.size) {
      next.size = update.size;
      changed = true;
    }
    if (update.cost && typeof update.cost === "object") {
      const cost = update.cost as { amount?: unknown; currency?: unknown };
      if (typeof cost.amount === "number" && next.costAmount !== cost.amount) {
        next.costAmount = cost.amount;
        changed = true;
      }
      if (
        typeof cost.currency === "string" &&
        next.costCurrency !== cost.currency
      ) {
        next.costCurrency = cost.currency;
        changed = true;
      }
    }
    if (!changed) {
      return true;
    }
    this.currentUsage = next;
    for (const handler of this.usageHandlers) {
      try {
        handler(next);
      } catch {
        void 0;
      }
    }
    return true;
  }

  // Update the cached agent command list, fire persist handlers, and
  // broadcast the merged list to attached clients. Idempotent on a
  // structurally identical list so we don't churn meta.json on noisy
  // re-emissions.
  private setAgentAdvertisedCommands(commands: AdvertisedCommand[]): void {
    if (sameAdvertisedCommands(this.agentAdvertisedCommands, commands)) {
      // Still broadcast — a fresh attach might be racing — but skip
      // persistence to avoid pointless meta.json writes.
      this.broadcastMergedCommands();
      return;
    }
    this.agentAdvertisedCommands = commands;
    for (const handler of this.agentCommandsHandlers) {
      try {
        handler(commands);
      } catch {
        void 0;
      }
    }
    this.broadcastMergedCommands();
  }

  // Subscribe to snapshot-state updates. SessionManager wires these to
  // persist the new value into meta.json so cold resurrect can restore
  // them via the attach response _meta.
  onAgentCommandsChange(
    handler: (commands: AdvertisedCommand[]) => void,
  ): void {
    this.agentCommandsHandlers.push(handler);
  }

  onModelChange(handler: (model: string) => void): void {
    this.modelHandlers.push(handler);
  }

  onModeChange(handler: (mode: string) => void): void {
    this.modeHandlers.push(handler);
  }

  onUsageChange(handler: (usage: UsageSnapshot) => void): void {
    this.usageHandlers.push(handler);
  }

  // Returns a freshly merged command list (hydra ∪ agent) for callers
  // that need a snapshot — notably acp-ws.ts's buildResponseMeta when
  // assembling the attach response.
  mergedAvailableCommands(): AdvertisedCommand[] {
    return [...hydraCommandsAsAdvertised(), ...this.agentAdvertisedCommands];
  }

  // The agent's own advertised commands (not merged with hydra verbs).
  // Used by SessionManager to persist into meta.json so cold resurrect
  // can re-deliver via the attach response _meta.
  agentOnlyAdvertisedCommands(): AdvertisedCommand[] {
    return [...this.agentAdvertisedCommands];
  }

  // Pick up an agent-emitted session_info_update and store its title
  // as our canonical record. The notification is also forwarded to
  // clients via the surrounding recordAndBroadcast call. Authoritative
  // — overrides our placeholder.
  private maybeApplyAgentSessionInfo(params: unknown): void {
    const obj = (params ?? {}) as { update?: unknown };
    const update = (obj.update ?? {}) as {
      sessionUpdate?: unknown;
      title?: unknown;
    };
    if (update.sessionUpdate !== "session_info_update") {
      return;
    }
    if (typeof update.title !== "string") {
      return;
    }
    const trimmed = update.title.trim();
    if (!trimmed || trimmed === this.title) {
      return;
    }
    this.title = trimmed;
    this.firstPromptSeeded = true;
    for (const handler of this.titleHandlers) {
      try {
        handler(trimmed);
      } catch {
        void 0;
      }
    }
  }

  // Dispatch a /hydra <verb> [args] slash command typed in any client's
  // composer. Returns a synthesized session/prompt response so the
  // caller's promise resolves like a normal turn. To add a verb: append
  // an entry to HYDRA_COMMANDS (drives validation + client advertising)
  // and a dispatch case in the switch below.
  private async handleSlashCommand(text: string): Promise<unknown> {
    const rest = text.slice("/hydra".length).trim();
    const match = rest.match(/^(\S+)(?:\s+([\s\S]*))?$/);
    const verb = match?.[1] ?? "";
    const arg = (match?.[2] ?? "").trim();
    if (verb === "") {
      // "/hydra" alone: no-op, return success so the user's
      // composer doesn't show an error.
      return { stopReason: "end_turn" };
    }
    if (!HYDRA_COMMANDS.some((c) => c.verb === verb)) {
      const known = HYDRA_COMMANDS.map((c) => c.verb).join(", ");
      const err = new Error(
        `unknown /hydra verb: ${verb} (known: ${known})`,
      ) as Error & { code: number };
      err.code = JsonRpcErrorCodes.InvalidParams;
      throw err;
    }
    switch (verb) {
      case "title":
        return this.runTitleCommand(arg);
      case "agent":
        return this.runAgentCommand(arg);
      case "kill":
        return this.runKillCommand();
      default: {
        // Listed in HYDRA_COMMANDS but no dispatch case — wired up wrong.
        const err = new Error(
          `no dispatcher for /hydra verb ${verb}`,
        ) as Error & { code: number };
        err.code = JsonRpcErrorCodes.InternalError;
        throw err;
      }
    }
  }

  // Runs as a normal queued prompt (so it serializes after any in-flight
  // turn). With an arg, sets the title directly. Without one, runs a
  // suppressed sub-prompt to the agent and uses its reply as the title.
  // Either path ends with setTitle, which broadcasts session_info_update
  // — that's what every other client observes.
  private runTitleCommand(arg: string): Promise<unknown> {
    return this.enqueuePrompt(async () => {
      if (arg) {
        this.setTitle(arg);
        return { stopReason: "end_turn" };
      }
      return this.runTitleRegen();
    });
  }

  private async runTitleRegen(): Promise<unknown> {
    const collected = await this.runInternalPrompt(
      "Reply with ONLY a short title (≤80 chars) summarizing this conversation so far. No quotes, no markdown, no explanation.",
    );
    const title = firstLine(collected.trim(), 80);
    if (title) {
      this.setTitle(title);
    }
    return { stopReason: "end_turn" };
  }

  // Send a prompt to the underlying agent and capture its reply chunks
  // privately (no fan-out to clients, no recording into history). Used
  // by /hydra title's regen path and /hydra agent's transcript-injection
  // path. Returns the joined agent_message_chunk text.
  private async runInternalPrompt(text: string): Promise<string> {
    if (this.internalPromptCapture) {
      throw new Error("internal prompt already in flight");
    }
    const capture: { chunks: string[] } = { chunks: [] };
    this.internalPromptCapture = capture;
    try {
      await this.agent.connection.request<unknown>("session/prompt", {
        sessionId: this.upstreamSessionId,
        prompt: [{ type: "text", text }],
      });
      return capture.chunks.join("");
    } finally {
      this.internalPromptCapture = undefined;
    }
  }

  // Swap the underlying agent process while keeping the same Session
  // record. Spawns the new agent first so a failure leaves the old one
  // intact; then injects a synthesized transcript so the new agent has
  // context for the next turn.
  private runAgentCommand(newAgentId: string): Promise<unknown> {
    if (!newAgentId) {
      throw withCode(
        new Error("/hydra agent requires an agent id"),
        JsonRpcErrorCodes.InvalidParams,
      );
    }
    if (newAgentId === this.agentId) {
      throw withCode(
        new Error(`already on agent ${newAgentId}`),
        JsonRpcErrorCodes.InvalidParams,
      );
    }
    if (!this.spawnReplacementAgent) {
      throw withCode(
        new Error("agent switching not configured for this session"),
        JsonRpcErrorCodes.InternalError,
      );
    }
    const spawnAgent = this.spawnReplacementAgent;
    return this.enqueuePrompt(async () => {
      const oldAgentId = this.agentId;
      const transcript = await this.buildSwitchTranscript(oldAgentId);

      const fresh = await spawnAgent({
        agentId: newAgentId,
        cwd: this.cwd,
        agentArgs: this.agentArgs,
      });
      this.wireAgent(fresh.agent);

      const oldAgent = this.agent;
      this.agent = fresh.agent;
      this.agentId = newAgentId;
      this.upstreamSessionId = fresh.upstreamSessionId;
      this.agentMeta = fresh.agentMeta;
      // Old agent's commands no longer apply; clear and re-broadcast
      // a merged update with just /hydra verbs until the new agent
      // advertises its own.
      this.agentAdvertisedCommands = [];
      this.broadcastMergedCommands();
      await oldAgent.kill().catch(() => undefined);

      if (transcript) {
        await this.runInternalPrompt(transcript).catch(() => undefined);
      }

      this.broadcastAgentSwitch(oldAgentId, newAgentId);

      const info = {
        agentId: this.agentId,
        upstreamSessionId: this.upstreamSessionId,
      };
      for (const handler of this.agentChangeHandlers) {
        try {
          handler(info);
        } catch {
          void 0;
        }
      }
      return { stopReason: "end_turn" };
    });
  }

  // Close this session in-place. Bypasses enqueuePrompt deliberately so a
  // mid-turn /hydra kill takes effect immediately — agent.kill() will tear
  // down any in-flight request as a side effect. The record is kept
  // (deleteRecord:false) so the session goes cold and can be resurrected.
  // Returns end_turn so the prompt() caller's response resolves normally,
  // but every attached client has already received hydra-acp/session_closed
  // by the time this returns.
  private async runKillCommand(): Promise<unknown> {
    await this.close({ deleteRecord: false });
    return { stopReason: "end_turn" };
  }

  // Walk the persisted history and produce a labeled transcript suitable
  // for handing to a fresh agent. Includes user prompts, agent replies,
  // and tool-call outcomes; skips hydra-synthesized markers (so multi-hop
  // switches don't accumulate banners) and other update kinds we don't
  // think the next agent benefits from re-seeing (plans, thoughts,
  // mode/model/usage).
  //
  // The header text defaults to the agent-swap framing; callers like
  // seedFromImport pass a custom header when the new agent is taking
  // over an imported session rather than swapping mid-conversation.
  private async buildSwitchTranscript(
    prevAgentId: string,
    headerOverride?: { intro: string; followup: string },
  ): Promise<string> {
    const lines: Array<{ speaker: string; text: string }> = [];
    const history = await this.getHistorySnapshot();
    for (const note of history) {
      if (note.method !== "session/update") {
        continue;
      }
      const params = (note.params ?? {}) as { update?: Record<string, unknown> };
      const update = params.update;
      if (!update) {
        continue;
      }
      const meta = update._meta as
        | { "hydra-acp"?: { synthetic?: boolean } }
        | undefined;
      if (meta?.["hydra-acp"]?.synthetic) {
        continue;
      }
      const kind = update.sessionUpdate as string | undefined;
      if (kind === "prompt_received") {
        const text = extractPromptText(update.prompt);
        if (text) {
          lines.push({ speaker: "user", text });
        }
      } else if (kind === "agent_message_chunk") {
        const content = update.content as { text?: string } | undefined;
        const text = content?.text;
        if (text) {
          lines.push({ speaker: `agent: ${prevAgentId}`, text });
        }
      } else if (kind === "tool_call" || kind === "tool_call_update") {
        const status = update.status as string | undefined;
        const title = update.title as string | undefined;
        if (status === "completed" || status === "failed") {
          lines.push({
            speaker: "tool",
            text: `${title ?? "?"} ${status}`,
          });
        }
      }
    }
    if (lines.length === 0) {
      return "";
    }
    // Coalesce consecutive same-speaker entries (chunks → paragraph).
    const coalesced: string[] = [];
    let current: { speaker: string; text: string } | undefined;
    for (const line of lines) {
      if (current && current.speaker === line.speaker) {
        current.text += line.text;
      } else {
        if (current) {
          coalesced.push(`<${current.speaker}>: ${current.text.trim()}`);
        }
        current = { speaker: line.speaker, text: line.text };
      }
    }
    if (current) {
      coalesced.push(`<${current.speaker}>: ${current.text.trim()}`);
    }
    const intro =
      headerOverride?.intro ??
      `You are taking over this conversation from ${prevAgentId}. Below is the transcript so far.`;
    const followup =
      headerOverride?.followup ??
      `Each line is prefixed with its speaker. Continue from where ${prevAgentId} left off, responding to the user's most recent message.`;
    return [
      intro,
      followup,
      "",
      "--- begin transcript ---",
      ...coalesced,
      "--- end transcript ---",
    ].join("\n");
  }

  // Replay the persisted history into a freshly-spawned agent so an
  // imported session has context. Called by SessionManager.doResurrect
  // on the first wake-up of a session whose meta.json has an empty
  // upstreamSessionId (the import marker). Wrapped in enqueuePrompt so
  // any user prompts arriving mid-seed queue behind it (mirrors the
  // /hydra agent path so the agent isn't asked to respond to a user
  // turn before it has absorbed the imported transcript). Best-effort:
  // if the agent fails to absorb the transcript we still leave the
  // session usable — the user just continues without context.
  async seedFromImport(): Promise<void> {
    await this.enqueuePrompt(async () => {
      const transcript = await this.buildSwitchTranscript(this.agentId, {
        intro:
          "You are continuing a conversation that was imported from another hydra. Below is the transcript so far.",
        followup:
          "Each line is prefixed with its speaker. Treat this as context for the next user message; do not re-respond to earlier turns.",
      });
      if (!transcript) {
        return undefined;
      }
      await this.runInternalPrompt(transcript).catch(() => undefined);
      return undefined;
    });
  }

  // Tell every attached client (a) the agent identity has changed
  // (session_info_update carrying agentId inside _meta["hydra-acp"] —
  // the ACP schema for session_info_update is just title/updatedAt/_meta,
  // so non-hydra clients harmlessly ignore the extension; hydra-aware
  // ones read it and relabel) and (b) drop a visible banner into the
  // transcript so users see the switch rather than just suddenly getting
  // answers from a different agent. Both updates carry synthetic=true
  // so a future /hydra agent's transcript builder filters them out.
  private broadcastAgentSwitch(oldAgentId: string, newAgentId: string): void {
    this.recordAndBroadcast("session/update", {
      sessionId: this.sessionId,
      update: {
        sessionUpdate: "session_info_update",
        _meta: { "hydra-acp": { synthetic: true, agentId: newAgentId } },
      },
    });
    this.recordAndBroadcast("session/update", {
      sessionId: this.sessionId,
      update: {
        sessionUpdate: "agent_message_chunk",
        content: {
          type: "text",
          text: `\n_(switched from \`${oldAgentId}\` to \`${newAgentId}\`)_\n`,
        },
        _meta: { "hydra-acp": { synthetic: true } },
      },
    });
  }

  private markClosed(opts: { deleteRecord: boolean }): void {
    if (this.closed) {
      return;
    }
    this.closed = true;
    this.cancelIdleTimer();
    for (const client of this.clients.values()) {
      void client.connection
        .notify("hydra-acp/session_closed", { sessionId: this.sessionId })
        .catch(() => undefined);
    }
    this.clients.clear();
    for (const handler of this.closeHandlers) {
      handler(opts);
    }
  }

  // Last meaningful activity timestamp. Bumped only by recordable
  // broadcasts in recordAndBroadcast — the same signal historyMtimeIso
  // uses for the picker. Initialized at construction (and seeded from
  // the newest entry on resurrect) so the inactivity window starts
  // ticking from a sensible floor when there's no history yet.
  private get lastActivityAt(): number {
    return this.lastRecordedAt;
  }

  // (Re-)arm the idle timer to fire when the inactivity window
  // elapses past lastActivityAt. Called once at construction and after
  // every recorded broadcast. The previous design gated on
  // clients.size === 0; we drop that gate because extensions
  // (slack/notifier/approver/browser) hold persistent attaches that
  // would otherwise keep a quiet session alive forever.
  private scheduleIdleCheck(): void {
    if (this.closed || this.idleTimeoutMs <= 0) {
      return;
    }
    const dueAt = this.lastActivityAt + this.idleTimeoutMs;
    this.armIdleTimer(Math.max(0, dueAt - Date.now()));
  }

  private armIdleTimer(delay: number): void {
    if (this.idleTimer) {
      clearTimeout(this.idleTimer);
    }
    this.idleTimer = setTimeout(() => {
      this.idleTimer = undefined;
      this.checkIdle();
    }, delay);
    if (typeof this.idleTimer.unref === "function") {
      this.idleTimer.unref();
    }
  }

  private checkIdle(): void {
    if (this.closed || this.idleTimeoutMs <= 0) {
      return;
    }
    // Never abandon active work. An in-flight turn or unresolved
    // permission request defers the close by a full idle window —
    // the next broadcast will re-arm us sooner anyway, and this
    // avoids a tight reschedule loop when activity is stale but
    // work is genuinely in flight.
    if (
      this.turnStartedAt !== undefined ||
      this.inFlightPermissions.size > 0
    ) {
      this.armIdleTimer(this.idleTimeoutMs);
      return;
    }
    const idle = Date.now() - this.lastActivityAt;
    if (idle < this.idleTimeoutMs) {
      this.armIdleTimer(this.idleTimeoutMs - idle);
      return;
    }
    // A session that never received a prompt has no conversation to
    // preserve; drop the record entirely instead of leaving an empty
    // cold session cluttering the picker. Otherwise persist as cold,
    // asking the agent for one last title summary on the way out.
    const opts: CloseOptions = this.firstPromptSeeded
      ? { deleteRecord: false, regenTitle: true }
      : { deleteRecord: true };
    const idleSec = Math.round(idle / 1000);
    this.logger?.info(
      `session ${this.sessionId} idle timeout fired after ${idleSec}s (window=${Math.round(this.idleTimeoutMs / 1000)}s) — closing`,
    );
    void this.close(opts).catch(() => undefined);
  }

  private cancelIdleTimer(): void {
    if (this.idleTimer) {
      clearTimeout(this.idleTimer);
      this.idleTimer = undefined;
    }
  }

  private rewriteForClient(params: unknown): unknown {
    if (params && typeof params === "object" && !Array.isArray(params)) {
      const obj = params as Record<string, unknown>;
      if (obj.sessionId === this.upstreamSessionId) {
        return { ...obj, sessionId: this.sessionId };
      }
    }
    return params;
  }

  private recordAndBroadcast(
    method: string,
    params: unknown,
    excludeClientId?: string,
  ): void {
    const rewritten = this.rewriteForClient(params);
    // Snapshot-shaped updates (title, model, mode, available commands)
    // are broadcast live but deliberately not recorded. Their canonical
    // state lives in meta.json and is delivered to fresh clients via
    // the attach response _meta. Replaying historical transitions would
    // just churn client state through stale values en route to the
    // current one.
    const recordable = !isStateUpdate(method, rewritten);
    // Stamp every recordable session/update with a messageId so
    // after_message replay has resync anchors at every event boundary
    // — not just prompt_received / turn_complete. Non-recordable
    // events (state updates) skip this since they're not in history,
    // and explicit messageIds (set by broadcastPromptReceived /
    // broadcastTurnComplete) are preserved.
    const broadcast = recordable
      ? ensureMessageIdOnUpdate(method, rewritten)
      : rewritten;
    if (recordable) {
      const entry: CachedNotification = {
        method,
        params: broadcast,
        recordedAt: Date.now(),
      };
      this.lastRecordedAt = entry.recordedAt;
      this.appendCount += 1;
      // Disk is the source of truth for replay. Append is fire-and-forget;
      // failures (full disk, permission problems) shouldn't block the
      // live broadcast. Periodic compaction trims the file in place when
      // it grows past the cap.
      if (this.historyStore) {
        const store = this.historyStore;
        void store.append(this.sessionId, entry).catch(() => undefined);
        if (this.appendCount >= this.compactEvery) {
          this.appendCount = 0;
          void store.compact(this.sessionId, this.historyMaxEntries).catch(
            () => undefined,
          );
        }
      }
      // Fan the recorded entry out to any tail-style subscribers
      // (currently the HTTP /history?follow=1 stream). Synchronous
      // dispatch so a subscriber sees the entry in order; handlers
      // own their own error handling.
      for (const handler of this.broadcastHandlers) {
        try {
          handler(entry);
        } catch {
          void 0;
        }
      }
      this.scheduleIdleCheck();
    }
    this.updatedAt = Date.now();
    for (const client of this.clients.values()) {
      if (excludeClientId && client.clientId === excludeClientId) {
        continue;
      }
      void client.connection.notify(method, broadcast).catch(() => undefined);
    }
  }

  private async handlePermissionRequest(params: unknown): Promise<unknown> {
    const initialClients = [...this.clients.values()];
    if (initialClients.length === 0) {
      throw withCode(
        new Error("no clients attached to handle permission request"),
        JsonRpcErrorCodes.PermissionDenied,
      );
    }
    const clientParams = this.rewriteForClient(params);
    const toolCallId = extractToolCallId(clientParams);
    return new Promise<unknown>((resolve, reject) => {
      let settled = false;
      const outbound: Array<{ client: AttachedClient }> = [];
      const entry = { addClient: sendTo };
      this.inFlightPermissions.add(entry);
      const sessionId = this.sessionId;

      const settle = (fn: () => void): void => {
        if (settled) {
          return;
        }
        settled = true;
        this.inFlightPermissions.delete(entry);
        fn();
      };

      function sendTo(client: AttachedClient): void {
        if (settled) {
          return;
        }
        const response = client.connection.request<unknown>(
          "session/request_permission",
          clientParams,
        );
        outbound.push({ client });
        void response
          .then((result) => {
            settle(() => {
              const update = buildPermissionResolvedUpdate({
                toolCallId,
                result,
                resolver: client,
              });
              for (const o of outbound) {
                if (o.client.clientId === client.clientId) {
                  continue;
                }
                void o.client.connection
                  .notify("session/update", {
                    sessionId,
                    update,
                  })
                  .catch(() => undefined);
              }
              resolve(result);
            });
          })
          .catch((err) => {
            settle(() => reject(err));
          });
      }

      for (const client of initialClients) {
        sendTo(client);
      }
    });
  }

  private async enqueuePrompt(task: () => Promise<unknown>): Promise<unknown> {
    return new Promise<unknown>((resolve, reject) => {
      const run = async (): Promise<void> => {
        try {
          const result = await task();
          resolve(result);
        } catch (err) {
          reject(err as Error);
        }
      };
      this.promptQueue.push(run);
      void this.drainQueue();
    });
  }

  private async drainQueue(): Promise<void> {
    if (this.promptInFlight) {
      return;
    }
    this.promptInFlight = true;
    try {
      while (this.promptQueue.length > 0) {
        const next = this.promptQueue.shift();
        if (next) {
          await next();
        }
      }
    } finally {
      this.promptInFlight = false;
    }
  }
}

function withCode(err: Error, code: number): Error & { code: number } {
  (err as Error & { code: number }).code = code;
  return err as Error & { code: number };
}

// session/update kinds that carry "what's currently true" snapshots
// rather than conversation events. Broadcast live but not recorded to
// history — the canonical state lives in meta.json and is delivered to
// fresh attaches via the attach response _meta.
const STATE_UPDATE_KINDS = new Set([
  "session_info_update",
  "current_model_update",
  "current_mode_update",
  "available_commands_update",
  "usage_update",
]);

function isStateUpdate(method: string, params: unknown): boolean {
  if (method !== "session/update") {
    return false;
  }
  const obj = (params ?? {}) as { update?: { sessionUpdate?: unknown } };
  const kind = obj.update?.sessionUpdate;
  return typeof kind === "string" && STATE_UPDATE_KINDS.has(kind);
}

function sameAdvertisedCommands(
  a: AdvertisedCommand[],
  b: AdvertisedCommand[],
): boolean {
  if (a.length !== b.length) {
    return false;
  }
  for (let i = 0; i < a.length; i++) {
    if (a[i]?.name !== b[i]?.name || a[i]?.description !== b[i]?.description) {
      return false;
    }
  }
  return true;
}

// Pull text out of an agent_message_chunk session/update notification
// and append it to a /hydra-slash-command's private capture buffer.
// Other update kinds (thoughts, tool calls, plans, etc.) are swallowed
// — we only need the prose reply.
function captureInternalChunk(
  capture: { chunks: string[] },
  params: unknown,
): void {
  const obj = (params ?? {}) as { update?: unknown };
  const update = (obj.update ?? {}) as {
    sessionUpdate?: unknown;
    content?: unknown;
  };
  if (update.sessionUpdate !== "agent_message_chunk") {
    return;
  }
  const content = (update.content ?? {}) as { text?: unknown };
  if (typeof content.text === "string") {
    capture.chunks.push(content.text);
  }
}

// Returns the agent-advertised command list when params is a session/update
// of kind available_commands_update; null otherwise. Used to intercept the
// agent's raw update so we can re-emit a merged (hydra ∪ agent) version
// to clients via broadcastMergedCommands.
function extractAdvertisedCommands(
  params: unknown,
): AdvertisedCommand[] | null {
  const obj = (params ?? {}) as { update?: unknown };
  const update = (obj.update ?? {}) as {
    sessionUpdate?: unknown;
    availableCommands?: unknown;
    commands?: unknown;
  };
  if (update.sessionUpdate !== "available_commands_update") {
    return null;
  }
  const list = update.availableCommands ?? update.commands;
  if (!Array.isArray(list)) {
    return [];
  }
  const out: AdvertisedCommand[] = [];
  for (const raw of list) {
    if (!raw || typeof raw !== "object") {
      continue;
    }
    const c = raw as { name?: unknown; description?: unknown };
    if (typeof c.name !== "string" || c.name.length === 0) {
      continue;
    }
    const cmd: AdvertisedCommand = { name: c.name };
    if (typeof c.description === "string") {
      cmd.description = c.description;
    }
    out.push(cmd);
  }
  return out;
}

// If `params` is a session/update with an `update` object that lacks
// a messageId, return a shallow clone with one stamped. Otherwise
// return `params` unchanged. Keeps the original caller-supplied
// object untouched so we don't surprise anyone holding a reference.
function ensureMessageIdOnUpdate(method: string, params: unknown): unknown {
  if (method !== "session/update" || !params || typeof params !== "object") {
    return params;
  }
  const p = params as { update?: unknown };
  if (!p.update || typeof p.update !== "object" || Array.isArray(p.update)) {
    return params;
  }
  const u = p.update as { messageId?: unknown };
  if (typeof u.messageId === "string") {
    return params;
  }
  return {
    ...(params as Record<string, unknown>),
    update: { ...(p.update as Record<string, unknown>), messageId: generateMessageId() },
  };
}

// Walk a history snapshot and find the index of the entry whose
// session/update.messageId matches `target`. Returns -1 if not found.
// Used by attach() to compute the after_message replay slice.
function findMessageIdIndex(
  history: CachedNotification[],
  target: string,
): number {
  for (let i = 0; i < history.length; i++) {
    const entry = history[i];
    if (!entry || entry.method !== "session/update") {
      continue;
    }
    const params = entry.params as { update?: { messageId?: unknown } } | undefined;
    if (params?.update?.messageId === target) {
      return i;
    }
  }
  return -1;
}

// Pull `toolCallId` out of the `session/request_permission` params we
// forward to clients. The wire shape is `{ sessionId, toolCall: { toolCallId, ... }, options }`.
// Returns undefined if the params don't match (defensive — agents that
// emit a malformed request_permission would already be off-spec).
function extractToolCallId(params: unknown): string | undefined {
  if (!params || typeof params !== "object") {
    return undefined;
  }
  const toolCall = (params as { toolCall?: unknown }).toolCall;
  if (!toolCall || typeof toolCall !== "object") {
    return undefined;
  }
  const id = (toolCall as { toolCallId?: unknown }).toolCallId;
  return typeof id === "string" ? id : undefined;
}

interface PermissionResolvedBuildArgs {
  toolCallId: string | undefined;
  result: unknown;
  resolver: AttachedClient;
}

// Build the `update` body for a `session/update`/`permission_resolved`
// notification per RFD #533 (with our proposed `outcome` extension carried
// alongside the spec-literal `chosenOptionId`).
function buildPermissionResolvedUpdate(
  args: PermissionResolvedBuildArgs,
): Record<string, unknown> {
  const outcome = extractOutcome(args.result);
  const update: Record<string, unknown> = {
    sessionUpdate: "permission_resolved",
  };
  if (args.toolCallId !== undefined) {
    update.toolCallId = args.toolCallId;
  }
  if (outcome) {
    update.outcome = outcome;
    if (outcome.kind === "selected" && typeof outcome.optionId === "string") {
      update.chosenOptionId = outcome.optionId;
    }
  }
  update.resolvedBy = buildResolvedBy(args.resolver);
  return update;
}

interface OutcomeShape {
  kind: string;
  optionId?: string;
  reason?: string;
}

function extractOutcome(result: unknown): OutcomeShape | undefined {
  if (!result || typeof result !== "object") {
    return undefined;
  }
  const raw = (result as { outcome?: unknown }).outcome;
  if (!raw || typeof raw !== "object") {
    return undefined;
  }
  const kind = (raw as { kind?: unknown }).kind;
  if (typeof kind !== "string") {
    return undefined;
  }
  const out: OutcomeShape = { kind };
  const optionId = (raw as { optionId?: unknown }).optionId;
  if (typeof optionId === "string") {
    out.optionId = optionId;
  }
  const reason = (raw as { reason?: unknown }).reason;
  if (typeof reason === "string") {
    out.reason = reason;
  }
  return out;
}

function buildResolvedBy(client: AttachedClient): Record<string, unknown> {
  const out: Record<string, unknown> = { clientId: client.clientId };
  if (client.clientInfo?.name) {
    out.name = client.clientInfo.name;
  }
  if (client.clientInfo?.version) {
    out.version = client.clientInfo.version;
  }
  return out;
}

export function extractPromptText(prompt: unknown): string {
  if (typeof prompt === "string") {
    return prompt;
  }
  if (!Array.isArray(prompt)) {
    return "";
  }
  return prompt
    .map((b) => {
      if (b && typeof b === "object" && typeof (b as { text?: unknown }).text === "string") {
        return (b as { text: string }).text;
      }
      return "";
    })
    .join("");
}

// First non-empty line of `text`, truncated to `max` chars with a
// trailing ellipsis if needed. Used to seed a session title from the
// first user prompt's leading line.
export function firstLine(text: string, max: number): string | undefined {
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line) {
      continue;
    }
    return line.length > max ? `${line.slice(0, max)}…` : line;
  }
  return undefined;
}
